#!/usr/bin/env bash
# deploy/generate-env.sh
# Generates a fresh .env.prod (in the repository root) with strong random
# secrets. Idempotent: refuses to overwrite an existing .env.prod unless
# called with --force.
#
# Usage:
#   bash deploy/generate-env.sh <PUBLIC_BASE_URL> [--force]
# Example:
#   bash deploy/generate-env.sh http://161.97.116.153:8080
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/.env.prod"

PUBLIC_BASE_URL="${1:-}"
if [[ -z "$PUBLIC_BASE_URL" ]]; then
  echo "Usage: $0 <PUBLIC_BASE_URL> [--force]" >&2
  echo "  e.g.: $0 http://161.97.116.153:8080" >&2
  exit 2
fi

FORCE=0
[[ "${2:-}" == "--force" ]] && FORCE=1

if [[ -e "$OUT" && $FORCE -ne 1 ]]; then
  echo "$OUT already exists. Re-run with --force to overwrite." >&2
  exit 1
fi

# Detect the host port from the public URL (default 8080) so the generated
# .env.prod stays consistent with what the user typed.
PORT="$(printf '%s' "$PUBLIC_BASE_URL" | sed -E 's#^https?://[^/:]+:?([0-9]+)?.*#\1#')"
[[ -z "$PORT" ]] && PORT=8080

rand_hex()    { openssl rand -hex 32; }                                       # 64 hex chars
rand_pass()   { openssl rand -base64 24 | tr -d '+/=\n' | cut -c1-24; }       # 24 url-safe chars

cat >"$OUT" <<EOF
# Generated by deploy/generate-env.sh on $(date -u +'%Y-%m-%dT%H:%M:%SZ')
# DO NOT commit this file.

# Postgres
POSTGRES_DB=crm_tradeway
POSTGRES_USER=crm_user
POSTGRES_PASSWORD=$(rand_pass)

# Redis
REDIS_PASSWORD=$(rand_pass)

# JWT (each ≥ 32 chars, distinct)
JWT_ACCESS_SECRET=$(rand_hex)
JWT_REFRESH_SECRET=$(rand_hex)

# Seed (super_admin + the other 6 default users will share this password)
SEED_DEFAULT_PASSWORD=$(rand_pass)

# Public URL config
PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
CORS_ALLOWED_ORIGINS=${PUBLIC_BASE_URL}
PUBLIC_DEFAULT_LOCALE=en

# Host port published by Nginx
PUBLIC_HTTP_PORT=${PORT}
EOF

chmod 600 "$OUT"
echo "Wrote $OUT"
echo "Super admin login password is in the SEED_DEFAULT_PASSWORD line."
